// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8LjCSiWbk00OrEmCJJBrDxvZ1AR-Td0',
    appId: '1:878649844417:web:c0f2ee5d2073c34c306a40',
    messagingSenderId: '878649844417',
    projectId: 'projectmobile-f2d0f',
    authDomain: 'projectmobile-f2d0f.firebaseapp.com',
    databaseURL: 'https://projectmobile-f2d0f-default-rtdb.firebaseio.com',
    storageBucket: 'projectmobile-f2d0f.appspot.com',
    measurementId: 'G-TW7H13ZHFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZoI-HMV10oFBvvaFt7NafrX2q7XxhBY',
    appId: '1:878649844417:android:24aebb25bf8dfbcd306a40',
    messagingSenderId: '878649844417',
    projectId: 'projectmobile-f2d0f',
    databaseURL: 'https://projectmobile-f2d0f-default-rtdb.firebaseio.com',
    storageBucket: 'projectmobile-f2d0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJxXGQpO-qHPi4i3FccAqMcBfTpBMow-I',
    appId: '1:878649844417:ios:ec75b74e483f2f3f306a40',
    messagingSenderId: '878649844417',
    projectId: 'projectmobile-f2d0f',
    databaseURL: 'https://projectmobile-f2d0f-default-rtdb.firebaseio.com',
    storageBucket: 'projectmobile-f2d0f.appspot.com',
    iosBundleId: 'com.example.myapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJxXGQpO-qHPi4i3FccAqMcBfTpBMow-I',
    appId: '1:878649844417:ios:06efe13e36dfc6e3306a40',
    messagingSenderId: '878649844417',
    projectId: 'projectmobile-f2d0f',
    databaseURL: 'https://projectmobile-f2d0f-default-rtdb.firebaseio.com',
    storageBucket: 'projectmobile-f2d0f.appspot.com',
    iosBundleId: 'com.example.myapp3.RunnerTests',
  );
}
